module.exports = {
  env: {
    browser: true,
    es6: true,
    node: true,
  },
  extends: [
    'plugin:react/recommended',
    'airbnb',
    'airbnb/hooks',
    'airbnb-typescript'
  ],
  parserOptions: {
    project: ['./tsconfig.json'],
    ecmaVersion: 'latest',
		sourceType: 'module',
  },
  plugins: [
    'react',
    'react-hooks',
  ],
  rules: {
    'no-multi-spaces': [2, { ignoreEOLComments: true, exceptions: { VariableDeclarator: true } }],
    'no-console': 0,
    'no-use-before-define': 'off',
    'react/jsx-filename-extension': [1, { extensions: ['.tsx'] }],
    'import/no-extraneous-dependencies': ['error', { packageDir: './' }],
    'padding-line-between-statements': [2, { blankLine: 'always', prev: ['const', 'let', 'var'], next: '*' }, { blankLine: 'any', prev: ['const', 'let', 'var'], next: ['const', 'let', 'var'] }],
    'no-multiple-empty-lines': [2, { max: 1 }],
    'react/destructuring-assignment': 0,
    'no-bitwise': 0,
    'no-plusplus': 0,
    'jsx-a11y/accessible-emoji': 0,
    eqeqeq: [1, 'smart'],
    'import/extensions': [1, { js: 'never', ts: 'never', json: 'always' }],
    '@typescript-eslint/no-floating-promises': [1, { ignoreVoid: false }],
    '@typescript-eslint/no-namespace': 0,
    'react/prop-types': 0,
    '@typescript-eslint/restrict-template-expressions': [2, { allowBoolean: true, allowAny: true, allowNullish: true }],
    indent: 'off',
    '@typescript-eslint/indent': ['error', 2],
    'react/function-component-definition': [1, { namedComponents: 'arrow-function', unamedComponents: '' }],
    'import/no-relative-packages': 0,
    'no-shadow': 0,
    '@typescript-eslint/no-shadow': 1,
    'function-paren-newline': 0,
  },
};
